### ISSUE TITLE
Integrate EPSG.io API into Georeference

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/www.staremapy.cz#46]
Add into Georeference tool a bar made in JavaScript which allows to:
- Search for a coordinate system with the EPSG.io API
- Allow user to type coordinates as numbers (easting/northing field)
- As a result show the Lat/Lon in alert() now - we provide you with an exported function to add a new GCP into Georeference in Gr3.

**Comment by klokan** [comment]
See lower bar in the video: https://youtu.be/by5sTBs1qOA?t=34s
Instead of "Remove" there should be "Change coordinate system".

**Comment by klokan** [comment]
API for search coordinates systems and API for transformation is described at:
https://github.com/klokantech/epsg.io#api-for-results

**Comment by dudaerich** [comment]
I suggest workflow shown in the picture.

![georeferencer-workflow](https://cloud.githubusercontent.com/assets/2317374/7373740/8d553716-edce-11e4-8621-51904b6d808d.png)

However the problem is that I am not able to detect situation when user clicks on the left map. I need API that enables me to register and unregister callback that will be called always when user adds point in the left map.

**Comment by klokan** [comment]
Well, I think the icon for adding the point must be on the right side - on a modern map. That's where the user adds a point - instead of clicking on a map. Maybe the dialog could somehow be framed within the right map div? An icon probably with "coordinate" or the symbol for adding the icon (?):
![screen shot 2015-04-29 at 10 26 15](https://cloud.githubusercontent.com/assets/59284/7387053/51ab8e68-ee5a-11e4-89cf-f3c61c07605e.png)
This one is from icomoon free set.

You will get an API exported function for adding a point on the reference map (right side), 
something `addPoint(lat,lng)` which will simulate clicking on the modern map.

**Comment by dudaerich** [comment]
Ok, It's clear me now. I'll change it in this way.

**Comment by dudaerich** [comment]
The feature is ready. See http://staremapy.georeferencer.cz/map/YBdnsXneDLS68dP9C5X06f/201505050404-L8koT6/georeference

**Comment by klokan** [comment]
Well done.

Unfortunately the terminology is completely wrong. Into the dialog people don't type only latitude and longitude ("Zemepisna sirka / delka") in degrees, but also projected coordinates (easting, northing) in meters or other units.

The correct terms are:

"Easting" = "východní souřadnice" - https://www.vugtk.cz/slovnik/termin.php?jazykova_verze=&tid=6456&l=easting-(e)

"Northing" = "severní souřadnice" - https://www.vugtk.cz/slovnik/termin.php?jazykova_verze=&tid=6455&l=northing-(n)

"Spatial Reference System" = "prostorový referenční systém" - https://www.vugtk.cz/slovnik/termin.php?jazykova_verze=&tid=1220&l=spatial-reference-system

I suggest to make the dialog a bit more usefriendly with phrases like:

"Zadat vlicovaci bod pomoci ciselnych souradnic"
"Vychod:" `'49.5' or '49 30' or '49 30.5' or '49 30 30'`
"Sever:" `'49.5' or '49 30' or '49 30.5' or '49 30 30'`
"Souradnicovy system:" `WGS84 or 4326 or 'jtsk' or 'czech'`

The input should make the degree transformation based on the space.
Perfect would be a clever input field which would for user replace the space with degree or minute sign.

Check:
goog.events.KeyHandler demo with "Number input" in http://closure-library.googlecode.com/git-history/0148f7ecaa1be5b645fabe7338b9579ed2f951c8/closure/goog/demos/index.html
and goog.ui.LabelInput

**Comment by dudaerich** [comment]
I have already started to change the dialog in way that each coordinate can be entered in three inputs. You can use only the first input and enter the coordinate as decimal number, for example 49.5° or you can use additional inputs and specify minutes and seconds.

So what do you prefer? One clever input or three inputs as they are shown in the screenshot?

![snimka obrazovky z 2015-05-05 16 22 30](https://cloud.githubusercontent.com/assets/2317374/7474655/0bb49650-f343-11e4-8148-b4bf00c26c04.png)

**Comment by klokan** [comment]
One is better then 3.

3 are incorrect for projected coordinates.

On Tuesday, May 5, 2015, Erich Duda <notifications@github.com> wrote:

> I have already started to change the dialog in way that each coordinate
> can be entered in three inputs. You can use only the first input and enter
> the coordinate as decimal number, for example 49.5° or you can use
> additional inputs and specify minutes and seconds.
>
> So what do you prefer? One clever input or three inputs as they are shown
> in the screenshot?
>
> [image: snimka obrazovky z 2015-05-05 16 22 30]
> <https://cloud.githubusercontent.com/assets/2317374/7474655/0bb49650-f343-11e4-8148-b4bf00c26c04.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moravianlibrary/www.staremapy.cz/issues/46#issuecomment-99093822>
> .
>


-- 
Petr Pridal, Ph.D.
(managing director)

Klokan Technologies GmbH
Hofnerstrasse 96, 6314 Unterageri, Switzerland
Tel: +41 (0)41 511 26 12
Email: info@klokantech.com
Web: http://www.klokantech.com/

**Comment by dudaerich** [comment]
Ok, I modified the dialog. The replacement of spaces with competent signes will be added later.

**Comment by dudaerich** [comment]
The dialog is ready now. I'm waiting for exporting a function, which adds a point on the reference map.

**Comment by klokan** [comment]
Thank you - the ball is now on my side.

**Comment by klokan** [comment]
It has been deployed @dudaerich.
Please turn on the dialog again.
